### ISSUE TITLE
Issue with Puppeteer after scanning QR code

### ISSUE THREAD

**Issue by jasonchanhku** [Zain-ul-din/whatsapp-ai-bot#12]
![image](https://github.com/Zain-ul-din/whatsapp-ai-bot/assets/20807220/f5a1eaeb-f099-45aa-98cd-fa0180a95f90)

Hi Zain, seems like there was some of kind change that break the application. It was going all good until this morning when I tried. I wonder what happened. Are you facing the same thing?

**Comment by jasonchanhku** [comment]
solved with
`npm i whatsapp-web.js@1.21.1-alpha.1`

**Comment by Zain-ul-din** [comment]
@jasonchanhku Good to hear Your issue has been solved🙂
