### ISSUE TITLE
Model's maximum context length exceed

### ISSUE THREAD

**Issue by yiwaixiao** [Zain-ul-din/whatsapp-ai-bot#16]
Thank you for providing the whatsapp-ai-bot. I tested it and it's a great application. However, I encountered the following issue during the trial. Whenever I engage in a few rounds of chat, I receive the following error. Is this a bug in the program or is there something that needs to be adjusted? Please advise.
```error
 ✖ CustomModel request fail | An error occur, at CustomModel.ts sendMessage(prompt, msg) err: Error: OpenAI error 400: {
    | ^
  2 | "error": {
  3 | "message": "This model's maximum context length is 4097 tokens. However, you requested 4246 tokens (1246 in the messages, 3000 in the completion). Please reduce the length of the messages or completion.",
  4 | "type": "invalid_request_error",
```

**Comment by Zain-ul-din** [comment]
@yiwaixiao this error is saying your maximum text limit has been exceeded.
check this error

```diff
- "message": "This model's maximum context length is 4097 tokens. 
- However, you requested 4246 tokens (1246 in the messages, 3000 in the completion). 
- Please reduce the length of the messages or completion."
``` 

### Possible Solution

1. Please reduce the length of the messages if your sending too long message.
2. Use `chat-gpt` latest models that have more token limit check out more [here](https://platform.openai.com/docs/models/gpt-4)

### To change the default model 

- go to source code `src/whatsapp-ai.config.ts`
- set `chatGPTModel: "gpt-3.5-turbo"` to `chatGPTModel: "gpt-4-32k"` **OR** add a model of your choice inside `chatGPTModel: "mode_name"`

![image](https://github.com/Zain-ul-din/whatsapp-ai-bot/assets/78583049/06364356-6ca9-4281-bc2a-c9136b4bbcff)



![image](https://github.com/Zain-ul-din/whatsapp-ai-bot/assets/78583049/2346b628-3106-4149-8999-7287431e2f52)

### Disclaimer ⚠

it is essential to note that these operations come at a cost charged by OpenAI and Stability AI for every request made. Please be aware that WhatsApp does not support bots or unofficial clients on its platform, so using this method is not entirely secure and could lead to getting blocked.

**Comment by yiwaixiao** [comment]
Thank you very much. I have successfully debugged it and will test it again. Thank you!
Also, may I ask if the prefix in the conversation can be empty, like prefix: '!dalle', for example: prefix: '', because in a customer service scenario, the customer may not know that a prefix is required. I have tested it, and when the prefix is set to '', the message will be repeatedly sent.

**Comment by yiwaixiao** [comment]
Thank you very much. The problem has been resolved
Also, may I ask if I could find a way to configure the openai API URL? I would like to use WhatsApp ai bot to connect with GPTs with knowledge base capabilities to enhance WhatsApp AI's customer service capabilities. The existing knowledge base GPT aligns with the official capabilities of the openai API, and only needs to be able to configure the openai API URL. For example, add a base URL field in:. env to customize the configuration of the openai API URL, without filling in the default support for the official openai API
May I ask if it is possible to support it? Please provide guidance. If not, can I upgrade and make changes? I can pay the appropriate fee. Thank you!

**Comment by zainuldeen** [comment]
I cannot understand your problem please can you provide some more details what do you means by `I could find a way to configure the openai API URL?`?

**Comment by Zain-ul-din** [comment]
Your question seems like **[XY Problem](https://xyproblem.info/)** please clearly describe what you exactly want to achieve also provide some examples if possible.

**Comment by yiwaixiao** [comment]
![QQ截图20231101095311](https://github.com/Zain-ul-din/whatsapp-ai-bot/assets/138955782/6b90e37e-cb21-4261-b799-254ee85b64be)
As shown in the example in the figure, add a 'BASE'_ URL. If this value is not filled in, it defaults to apiopenai.com. If it is filled in, use 'BASE'_ URL to request openai

**Comment by Zain-ul-din** [comment]
Check this package [chatgpt](https://www.npmjs.com/package/chatgpt) i'm using in this repository.

**Comment by yiwaixiao** [comment]
> As shown in the example in the figure, add a 'BASE'_ URL. If this value is not filled in, it defaults to apiopenai.com. If it is filled in, use 'BASE'_ URL to request openai

![QQ截图20231101095311](https://github.com/Zain-ul-din/whatsapp-ai-bot/assets/138955782/93b9f377-858d-4f65-95be-3cc408f28667)
As shown in the example in the figure, add a 'BASE'_ URL. If this value is not filled in, it defaults to apiopenai.com. If it is filled in, use 'BASE'_ URL to request openai

**Comment by zainuldeen** [comment]
still, I'm not getting please explain what exactly you want to achieve. You're thinking you managed to achieve X your Y problem will be solved automatically. So, Instead of describing X problem explain exactly `what you want to achieve.` 

[read about XY problem](https://xyproblem.info/)

**Comment by yiwaixiao** [comment]
Simply put, to be able to customize the OpenAI API endpoint in the .env file. By default, the whatsapp-ai-bot communicates with the OpenAI API using https://api.openai.com/v1. Now, I need to be able to customize the OpenAI API address in the .env file, for example, change it to https://api.abc.com/v1.

**Comment by Zain-ul-din** [comment]
I'm using [chat-gpt](https://www.npmjs.com/package/chatgpt) package. This package is responsible for sending requests to OPEN AI you can go to their repo and ask same question i think they can help you
