### ISSUE TITLE
QR-Code Problem

### ISSUE THREAD

**Issue by XamelionAG** [Zain-ul-din/whatsapp-ai-bot#21]
Hello, is there a way to save the QR code to a image file? 

I can't scan it with my mobile cuz it's not readable. 

Look screenshot, pls. 
![Screenshot_2024-02-08-05-46-11-771_com server auditor ssh client](https://github.com/Zain-ul-din/whatsapp-ai-bot/assets/138304877/8c2410b8-e162-468c-8cbd-d852eea33990)

**Comment by Zain-ul-din** [comment]
Consider cloning this branch this uses sockets and generate QR code on http://localhost:5173/ after you run it

https://github.com/Zain-ul-din/whatsapp-ai-bot/tree/sockets
