### ISSUE TITLE
Version 3.0 Iteration Plan 

### ISSUE THREAD

**Issue by Zain-ul-din** [Zain-ul-din/whatsapp-ai-bot#24]
## General proposal

- [ ] Implementation of web interface & bind data with front-end using `web-sockets`
 - [ ] generate QR code on the web instead of the terminal since many users facing #21 
 - [ ] display conversation on the front-end application.
 - [ ] Allow users to add API keys from the front-end application and store credentials in local DB.
 - [ ] Implement `rate-limiting`, `include-sender`, `exclude-sender` features for each AI model.
 
 ### Definitions
 
 - `rate-limiting` determines how many requests a sender can send for a given number of times. for example: User X can send 10 requests per min. #23 
 - `include-sender` allows sender only if 'include-sender' list contains the sender number 
 - `exclude-sender` disallows sender if 'exclude-sender' list contains the sender number
 
 ### Get Started
 
 fork this [branch](https://github.com/Zain-ul-din/whatsapp-ai-bot/tree/sockets) to contribute.

**Comment by levitco** [comment]
Would try to work on this enhancement on my end :) great project

**Comment by Zain-ul-din** [comment]
@levitco Thank you for showing your intention to contribute. Please tell us about your experience and how can you enhance this project.
