### ISSUE TITLE
http://localhost:5173/

### ISSUE THREAD

**Issue by hermesnunes** [Zain-ul-din/whatsapp-ai-bot#35]
http://[localhost](http://localhost:5173/):5173/ ERRO, after inserting the key keys it boots, but tries to open a window and gives an error, I don't know what to do, can you help: I wanted to do something more complete with your system, we can coopeer together: Teenho Csure we can be good partners here in Brazil, my contact, 5511984325192, call me please, you have great ideas, congratulations!

**Comment by Zain-ul-din** [comment]
@hermesnunes can you send me error you are getting or paste video here
