### ISSUE TITLE
Latest whatsapp-web.js update

### ISSUE THREAD

**Issue by MrUnforsaken** [Zain-ul-din/whatsapp-ai-bot#39]
With the latest whatsapp-web.js there seems to be a problem when loading chats. Because WWeb broke webcache, there was an special update for this: github:pedroslopez/whatsapp-web.js#webpak-exodus

After QR has been generated, you receive the following messages:
User Authenticated!
User Authenticated!
loading chat...

And never stays there forever (in a loop). Chat never gets loaded and therefore, Client is never ready. 

Any suggestion or help its appreciated.

**Comment by Zain-ul-din** [comment]
please share some screenshots or video

**Comment by azharpower** [comment]
https://github.com/Zain-ul-din/whatsapp-ai-bot/assets/169881159/78434c82-f06d-4de6-ae24-df32603f68c9
