### ISSUE TITLE
Latest whatsapp-web.js update

### ISSUE THREAD

**Issue by azharpower** [Zain-ul-din/whatsapp-ai-bot#40]
ith the latest whatsapp-web.js there seems to be a problem when loading chats. Because WWeb broke webcache, there was an special update 

After QR has been generated, you receive the following messages:

User Authenticated!
loading chat...

And never stays there forever (in a loop). Chat never gets loaded and therefore, Client is never ready.

Any suggestion or help its appreciated.

https://github.com/Zain-ul-din/whatsapp-ai-bot/assets/169881159/a517c553-25de-449b-bb7d-c2d26ca795e4

**Comment by Zain-ul-din** [comment]
What Platform are you using Windows? i just tested it's working on GitHub codespaces. [track here for update](https://github.com/Zain-ul-din/whatsapp-ai-bot/issues/25#issuecomment-2105970093)

**Comment by azharpower** [comment]
I tested it in my desktop windows 11 and my laptop Windows 10 .It was working fine since last 2 weeks anyway I will also try to test it in GitHub codespaces and I will send you the result .

**Comment by azharpower** [comment]
https://github.com/Zain-ul-din/whatsapp-ai-bot/assets/169881159/95ada165-0b93-4347-b9bd-0ae726133c5b

I got the same error.

**Comment by Zain-ul-din** [comment]
@azharpower Thank you for your patience. currently, I'm busy you can maybe see the fix this weekend.

**Comment by Keyz400** [comment]
> ith the latest whatsapp-web.js there seems to be a problem when loading chats. Because WWeb broke webcache, there was an special update
> 
> After QR has been generated, you receive the following messages:
> 
> User Authenticated! loading chat...
> 
> And never stays there forever (in a loop). Chat never gets loaded and therefore, Client is never ready.
> 
> Any suggestion or help its appreciated.
> 
>  RUST.2024.04.18.-.22.31.26.03.-.Trim.mp4

Solution?

**Comment by Keyz400** [comment]
Any solution for it

**Comment by Zain-ul-din** [comment]
@Keyz400 Not yet. I'm looking for a contributor
