### ISSUE TITLE
Command failed with exit code 1.

### ISSUE THREAD

**Issue by ZeanArd** [Zain-ul-din/whatsapp-ai-bot#49]
[1/3] ⠁ puppeteer
[2/3] ⠁ puppeteer
error /root/WhatsApp-Ai-bot/node_modules/whatsapp-web.js/node_modules/puppeteer: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: /root/WhatsApp-Ai-bot/node_modules/whatsapp-web.js/node_modules/puppeteer
Output:
The chromium binary is not available for arm64.
If you are on Ubuntu, you can install with:

 sudo apt install chromium

 sudo apt install chromium-browser

/root/WhatsApp-Ai-bot/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:119
                    throw new Error();
                    ^

Error
    at /root/WhatsApp-Ai-bot/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:119:27
    at FSReqCallback.oncomplete (node:fs:198:21)

Node.js v22.3.0
                                                                       
✔ dependencies has been installed
initializing server
yarn run v1.22.22
warning ../package.json: No license field
$ vite-node ./src/index.ts
node:internal/dns/promises:86
    this.reject(new DNSException(err, 'getaddrinfo', this.hostname));
                ^

Error: getaddrinfo ENOTFOUND localhost
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:internal/dns/promises:86:17) {
  errno: -3007,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'localhost'
}

Node.js v22.3.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Zain-ul-din** [comment]
if you look into the error there is a solution inside it,

If you are on Ubuntu, you can install with:

```shell
sudo apt install chromium
sudo apt install chromium-browser
```

**Comment by ZeanArd** [comment]
Done in 22.93s.
✔ dependencies has been installed
initializing server
yarn run v1.22.22
warning ../package.json: No license field
$ vite-node ./src/index.ts
node:internal/dns/promises:86
    this.reject(new DNSException(err, 'getaddrinfo', this.hostname));
                ^

Error: getaddrinfo ENOTFOUND localhost
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:internal/dns/promises:86:17) {
  errno: -3007,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'localhost'
}

Node.js v22.3.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.


Just the same

**Comment by Zain-ul-din** [comment]
fixed?

**Comment by ZeanArd** [comment]
Nope

**Comment by Zain-ul-din** [comment]
have you tried on GitHub codespace?

**Comment by ZeanArd** [comment]
It works, meaning my termux does not support it 😅, sorry for bothering you 😅
