### ISSUE TITLE
Every time it says i cant do this but can provide you tips regarding that?

### ISSUE THREAD

**Issue by askfriends** [Zain-ul-din/whatsapp-ai-bot#5]
i managed to make it work but every time i ask something it says i can't do this but can provide you tips regarding how to do that, which makes it useless, however, official chatgpt on openai.com is very useful and it does everything we ask it. So seems like this one uses an old model may be, can you fix it?
and Btw how to stop the bot on codespace?

**Comment by Zain-ul-din** [comment]
### Maybe I'll update it. if you can you're welcome to contribution.

**How to stop the bot on codespace?**
### Simply delete running code spaces

![image](https://user-images.githubusercontent.com/78583049/233295756-0cb7380a-090f-4c32-8115-7813fa7bda86.png)

**Comment by askfriends** [comment]
> > BTW is it fine to keep it running in codespace?
> 
> it's up to you to plan you have a limited quota of codespaces usage on GitHub. Of course, GitHub will cut off from this quota. code spaces have a limit of time which is 4 hours after 4 hours codespace will be closed automatically.
> 
> instead, you cloud use Heroku, Replit, railway, or another platform

i see, will you add support for all above mentioned free servers deploy using buttons?

**Comment by Zain-ul-din** [comment]
sure i'll

**Comment by Zain-ul-din** [comment]
@askfriends please recheck again

**Comment by askfriends** [comment]
> @askfriends please recheck again

kindly add support for deploying above mentioned servers

**Comment by Zain-ul-din** [comment]
@askfriends Already added for Heroku

**Comment by askfriends** [comment]
> @askfriends Already added for [Heroku](https://heroku.com/deploy?template=https://github.com/Zain-ul-din/whatsapp-ai-bot)

thanks bor for adding heroku support, but im planning to deploy it to some other free server which requires Procfile, so will u add that too?

**Comment by Zain-ul-din** [comment]
https://blog.logrocket.com/heroku-alternatives-deploy-node-js-app/#paid-options
