### ISSUE TITLE
DALL-E not working

### ISSUE THREAD

**Issue by rikuddo91** [Zain-ul-din/whatsapp-ai-bot#52]
OpenAI text and Gemini work perfectly, but when I try Dall-E, it just post `Hi It's WAAI BOT here 🤖` 

I've tried removing and re-linking everything again, but still get same message.

**Comment by Zain-ul-din** [comment]
As listed in the disclaimer only the following models are supported so far, wait for its support

![image](https://github.com/user-attachments/assets/58f16299-4b17-4ade-abc2-e6920c40b997)

**Comment by Zain-ul-din** [comment]
@rikuddo91 available now https://github.com/Zain-ul-din/whatsapp-ai-bot/commit/890f7c245053ba8f52bddb3a6faa5e1dbad42ea9
