### ISSUE TITLE
DALL-E return 'Model 'undefined' not found'

### ISSUE THREAD

**Issue by rikuddo91** [Zain-ul-din/whatsapp-ai-bot#62]
Hi, everything else is working fine, gpt, gemini, but when I try to use Dall-E it return 'Model 'undefined' not found'.

I have it Enabled as well as tried turning Dall-E 3 setting on and off, but both returned with same issue.
Currently it's like this,

DALLE_PREFIX=!dalle
DALLE_ENABLED=True
DALLE_ICON_PREFIX=🎨
DALLE_USE_3=True

**Comment by Zain-ul-din** [comment]
@rikuddo91 It has been resolved please test again

**Comment by rikuddo91** [comment]
> @rikuddo91 It has been resolved please test again

Thank you for quick reply I just tried with simple '!dalle cake' and it returned the following error on console,

`{"level":30,"time":"2024-10-24T10:03:51.219Z","pid":11200,"hostname":"DESKTOP-TRB6LE0","class":"baileys","msg":"handled 0 offline messages/notifications"}
BadRequestError: 400 The size is not supported by this model.
    at Function.generate (file:///E:/Temp/whatsapp-ai-bot/node_modules/openai/src/error.ts:70:14)
    at OpenAI.makeStatusError (file:///E:/Temp/whatsapp-ai-bot/node_modules/openai/src/core.ts:435:21)
    at OpenAI.makeRequest (file:///E:/Temp/whatsapp-ai-bot/node_modules/openai/src/core.ts:499:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ChatGPTModel.generateImage (E:\Temp\whatsapp-ai-bot\src\models\OpenAIModel.ts:30:17)
    at ChatGPTModel.sendMessage (E:\Temp\whatsapp-ai-bot\src\models\OpenAIModel.ts:42:21) {
  status: 400,
  headers: {
    'access-control-allow-origin': '*',
    'alt-svc': 'h3=":443"; ma=86400',
    'cf-cache-status': 'DYNAMIC',
    'cf-ray': '8d7923ee7e6ec301-VIE',
    connection: 'keep-alive',
    'content-length': '163',
    'content-type': 'application/json',
    date: 'Thu, 24 Oct 2024 10:04:02 GMT',
    'openai-organization': 'familyorg',
    'openai-processing-ms': '29',
    'openai-version': '2020-10-01',
    server: 'cloudflare',
    'set-cookie': '__cf_bm=OdbvbmXWvQvFK7IDvfsGw0N_FLf_S9JiL2ujG1uZdDY-1729764242-1.0.1.1-j8LP2oLykF4Pg3qkI0pTARJz74JR4LLmY1tFo6Y2WjMyqOhfe5tqVA6XaMZFpsM5g_sWC9uyxWL1W1NtG.jzFQ; path=/; expires=Thu, 24-Oct-24 10:34:02 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None, _cfuvid=fzEFrZDAKznmwyeN0Q4LcLIadg_TcrRaPB3rgFTbV8A-1729764242199-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None',
    'strict-transport-security': 'max-age=31536000; includeSubDomains; preload',
    'x-content-type-options': 'nosniff',
    'x-request-id': 'req_9aacbf2d62e03b140f7e10938e7a09b8'
  },
  request_id: 'req_9aacbf2d62e03b140f7e10938e7a09b8',
  error: {
    code: 'invalid_size',
    message: 'The size is not supported by this model.',
    param: null,
    type: 'invalid_request_error'
  },
  code: 'invalid_size',
  param: null,
  type: 'invalid_request_error'
}`

**Comment by Zain-ul-din** [comment]
@rikuddo91 wait let me see

**Comment by Zain-ul-din** [comment]
I think size specified here is not valid https://github.com/Zain-ul-din/whatsapp-ai-bot/blob/master/src/models/OpenAIModel.ts#L54

Please provide more information are you using dalle-2 or dalle-2?

**Comment by rikuddo91** [comment]
> I think size specified here is not valid https://github.com/Zain-ul-din/whatsapp-ai-bot/blob/master/src/models/OpenAIModel.ts#L54
> 
> Please provide more information are you using dalle-2 or dalle-3?

Using DallE-3, I tried changing that resolution to 1024x1024 but it crash after I try the prompt with following error,

```E:\Temp\whatsapp-ai-bot\node_modules\@whiskeysockets\baileys\lib\Utils\messages.js:76
        throw new boom_1.Boom('Invalid media type', { statusCode: 400 });
              ^

Error: Invalid media type
    at prepareWAMessageMedia (E:\Temp\whatsapp-ai-bot\node_modules\@whiskeysockets\baileys\lib\Utils\messages.js:76:15)
    at generateWAMessageContent (E:\Temp\whatsapp-ai-bot\node_modules\@whiskeysockets\baileys\lib\Utils\messages.js:415:53)
    at generateWAMessage (E:\Temp\whatsapp-ai-bot\node_modules\@whiskeysockets\baileys\lib\Utils\messages.js:507:102)
    at Object.sendMessage (E:\Temp\whatsapp-ai-bot\node_modules\@whiskeysockets\baileys\lib\Socket\messages-send.js:626:69)
    at E:\Temp\whatsapp-ai-bot\src\baileys\handlers\message.ts:64:16
    at ChatGPTModel.sendMessage (E:\Temp\whatsapp-ai-bot\src\models\OpenAIModel.ts:43:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 400,
    payload: {
      statusCode: 400,
      error: 'Bad Request',
      message: 'Invalid media type'
    },
    headers: {}
  }
}

Node.js v18.18.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.```

**Comment by Zain-ul-din** [comment]
@vicentefelipechile Can you check how you are checking res.image thing?

https://github.com/Zain-ul-din/whatsapp-ai-bot/blob/master/src/baileys/handlers/message.ts#L70

**Comment by Zain-ul-din** [comment]
@rikuddo91 please test again

**Comment by rikuddo91** [comment]
> @rikuddo91 please test again

Worked for Dall-E 2 but when I enable Dall-E 3 I get the following error,

```{"level":30,"time":"2024-10-24T15:47:17.926Z","pid":6656,"hostname":"DESKTOP-TRB6LE0","class":"baileys","msg":"handled 0 offline messages/notifications"}
BadRequestError: 400 The size is not supported by this model.
    at Function.generate (file:///E:/Temp/whatsapp-ai-bot/node_modules/openai/src/error.ts:70:14)
    at OpenAI.makeStatusError (file:///E:/Temp/whatsapp-ai-bot/node_modules/openai/src/core.ts:435:21)
    at OpenAI.makeRequest (file:///E:/Temp/whatsapp-ai-bot/node_modules/openai/src/core.ts:499:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ChatGPTModel.generateImage (E:\Temp\whatsapp-ai-bot\src\models\OpenAIModel.ts:31:17)
    at ChatGPTModel.sendMessage (E:\Temp\whatsapp-ai-bot\src\models\OpenAIModel.ts:45:21) {
  status: 400,
  headers: {
    'access-control-allow-origin': '*',
    'alt-svc': 'h3=":443"; ma=86400',
    'cf-cache-status': 'DYNAMIC',
    'cf-ray': '8d7b1d639ecb3257-VIE',
    connection: 'keep-alive',
    'content-length': '163',
    'content-type': 'application/json',
    date: 'Thu, 24 Oct 2024 15:49:05 GMT',
    'openai-organization': 'familyorg',
    'openai-processing-ms': '27',
    'openai-version': '2020-10-01',
    server: 'cloudflare',
    'set-cookie': '__cf_bm=ZeDYy8ARAGWkMjYXCi2mzxS8rQZKVMRXlceormtosbg-1729784945-1.0.1.1-GjvlzJz7u9uss_mLrzfpvkoiInUh.jLTRNl4WMUyowZk080m9d.gvO4IeHPB453LfMH.CGQ4Mb5x8IOn9TxlFg; path=/; expires=Thu, 24-Oct-24 16:19:05 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None, _cfuvid=dKxqPdtQyoZkjjwH8VQUbarsoLzQTH3N0nHPH5qacTQ-1729784945406-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None',
    'strict-transport-security': 'max-age=31536000; includeSubDomains; preload',
    'x-content-type-options': 'nosniff',
    'x-request-id': 'req_5e423afce3790a179959a820b8e3dd26'
  },
  request_id: 'req_5e423afce3790a179959a820b8e3dd26',
  error: {
    code: 'invalid_size',
    message: 'The size is not supported by this model.',
    param: null,
    type: 'invalid_request_error'
  },
  code: 'invalid_size',
  param: null,
  type: 'invalid_request_error'
}```

**Comment by vicentefelipechile** [comment]
> > @rikuddo91 please test again
> 
> Worked for Dall-E 2 but when I enable Dall-E 3 I get the following error,
> 
> ```
> {"level":30,"time":"2024-10-24T15:47:17.926Z","pid":6656,"hostname":"DESKTOP-TRB6LE0","class":"baileys","msg":"handled 0 offline messages/notifications"}
> BadRequestError: 400 The size is not supported by this model.
>     at Function.generate (file:///E:/Temp/whatsapp-ai-bot/node_modules/openai/src/error.ts:70:14)
>     at OpenAI.makeStatusError (file:///E:/Temp/whatsapp-ai-bot/node_modules/openai/src/core.ts:435:21)
>     at OpenAI.makeRequest (file:///E:/Temp/whatsapp-ai-bot/node_modules/openai/src/core.ts:499:24)
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at ChatGPTModel.generateImage (E:\Temp\whatsapp-ai-bot\src\models\OpenAIModel.ts:31:17)
>     at ChatGPTModel.sendMessage (E:\Temp\whatsapp-ai-bot\src\models\OpenAIModel.ts:45:21) {
>   status: 400,
>   headers: {
>     'access-control-allow-origin': '*',
>     'alt-svc': 'h3=":443"; ma=86400',
>     'cf-cache-status': 'DYNAMIC',
>     'cf-ray': '8d7b1d639ecb3257-VIE',
>     connection: 'keep-alive',
>     'content-length': '163',
>     'content-type': 'application/json',
>     date: 'Thu, 24 Oct 2024 15:49:05 GMT',
>     'openai-organization': 'familyorg',
>     'openai-processing-ms': '27',
>     'openai-version': '2020-10-01',
>     server: 'cloudflare',
>     'set-cookie': '__cf_bm=ZeDYy8ARAGWkMjYXCi2mzxS8rQZKVMRXlceormtosbg-1729784945-1.0.1.1-GjvlzJz7u9uss_mLrzfpvkoiInUh.jLTRNl4WMUyowZk080m9d.gvO4IeHPB453LfMH.CGQ4Mb5x8IOn9TxlFg; path=/; expires=Thu, 24-Oct-24 16:19:05 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None, _cfuvid=dKxqPdtQyoZkjjwH8VQUbarsoLzQTH3N0nHPH5qacTQ-1729784945406-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None',
>     'strict-transport-security': 'max-age=31536000; includeSubDomains; preload',
>     'x-content-type-options': 'nosniff',
>     'x-request-id': 'req_5e423afce3790a179959a820b8e3dd26'
>   },
>   request_id: 'req_5e423afce3790a179959a820b8e3dd26',
>   error: {
>     code: 'invalid_size',
>     message: 'The size is not supported by this model.',
>     param: null,
>     type: 'invalid_request_error'
>   },
>   code: 'invalid_size',
>   param: null,
>   type: 'invalid_request_error'
> }
> ```

Dalle 3 supports other types of resolutions, here is a table:

| Model | Resolution |
| ------- | ------------ |
| Dalle 2 | `256x256`, `512x512` or `1024x1024` |
| Dalle 3 | `1024x1024`, `1792x1024` or `1024x1792` |

You can check in detail more about this:
https://platform.openai.com/docs/api-reference/images/create#images-create-size

**Comment by Zain-ul-din** [comment]
@rikuddo91 try dalle-3 one more time so we can mark this as completed

**Comment by rikuddo91** [comment]
> @rikuddo91 try dalle-3 one more time so we can mark this as completed

Works now! Thank you so much for the patience :)

Just one more suggestion, would it be possible to add the line to change the GPT Model in the .env file itself? For now, it seems to be in "src\baileys\env.ts".

**Comment by Zain-ul-din** [comment]
I think it is available here https://github.com/Zain-ul-din/whatsapp-ai-bot/blob/master/src/baileys/env.ts#L66

**Comment by Zain-ul-din** [comment]
@vicentefelipechile Really appreciate your contribution 👏
