### ISSUE TITLE
TypeError: data.id.id.substring is not a function

### ISSUE THREAD

**Issue by ColAsTR** [Zain-ul-din/whatsapp-ai-bot#7]
I encountered an error while running the code that utilizes the this program.

 The error message indicates a TypeError at line 91 of the Message.js file.

/workspaces/whatsapp-ai-bot/node_modules/whatsapp-web.js/src/structures/Message.js:91
        this.deviceType = data.id.id.length > 21 ? 'android' : data.id.id.substring(0, 2) == '3A' ? 'ios' : 'web';
                                                                          ^

TypeError: data.id.id.substring is not a function
    at Message._patch (/workspaces/whatsapp-ai-bot/node_modules/whatsapp-web.js/src/structures/Message.js:91:75)
    at new Message (/workspaces/whatsapp-ai-bot/node_modules/whatsapp-web.js/src/structures/Message.js:18:24)
    at Client.sendMessage (/workspaces/whatsapp-ai-bot/node_modules/whatsapp-web.js/src/Client.js:699:16)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v19.9.0
error Command failed with exit code 1.

if you can just explain to me ways to solve this issue i will be gratefull.

thank you

**Comment by Zain-ul-din** [comment]
The error message suggests that there is a `TypeError` in the `Message.js` file of the `whatsapp-web.js` module. Specifically, the error occurs on line 91 of the `Message.js` file. 

The error message states that `data.id.id.substring` is not a function, which means that the `substring` method is being called on an object that doesn't have that method. 

To resolve this issue, you can try the following steps:

1. Update Node.js: Ensure that you are using a compatible version of Node.js. The error message you provided mentions Node.js v19.9.0, which seems to be a non-existent version. Update to a stable and supported version of Node.js, such as the latest LTS version.

2. Update the `whatsapp-web.js` module: Update the `whatsapp-web.js` module to the latest version. You can do this by running the following command in your project directory:
   ```
   npm update whatsapp-web.js
   ```

3. Clear npm cache: Clear the npm cache to avoid any potential conflicts. Run the following command:
   ```
   npm cache clean --force
   ```

4. Check data structure: Check the structure of the `data` object being passed to the `Message` class. Ensure that `data.id` is an object with an `id` property that is a string.
